# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodingChallenge

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.5'
    pod 'NVActivityIndicatorView'
    pod 'ReachabilitySwift'
    pod 'IQKeyboardManagerSwift'

  target 'CodingChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodingChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

